### ISSUE TITLE
RoleManager->Permissions error

### ISSUE THREAD

**Issue by abiusx** [OWASP/rbac#14]
If onlyIds is false, the query should be:
            return jf::SQL ( "SELECT `TP`.\* FROM {$this->tablePrefix()}rolepermissions AS `TR`
            RIGHT JOIN {$this->tablePrefix()}permissions AS `TP` ON (`TR`.PermissionID=`TP`.ID)
            WHERE RoleID=? ORDER BY TP.ID", $Role );
instead of
            return jf::SQL ( "SELECT `TP`.\* FROM {$this->tablePrefix()}rolepermissions AS `TR`
            RIGHT JOIN {$this->tablePrefix()}permissions AS `TP` ON (`TR`.PermissionID=`TP`.ID)
            WHERE RoleID=? ORDER BY TP.PermissionID", $Role );

**Comment by abiusx** [comment]
Same goes for PermissionManager->Roles

**Comment by jburns131** [comment]
This problem for 'RoleManager->Permissions' was resolved in commit b1e7c60.

This problem is not present for the 'PermissionManager->Roles' method in the most up-to-date branch at the moment (dev/v2-stable/commits), and I have not been able to narrow down which commit resolved this issue.

Please verify that this Issue is complete and I will close this Issue.

Thanks!

**Comment by abiusx** [comment]
This only happens in rare cases, just check the code and Replace PermissionID with ID in the mentioned part.
