### ISSUE TITLE
Checking for dynamic 'owner' role possible?

### ISSUE THREAD

**Issue by bblue** [OWASP/rbac#19]
(I am new to the whole rbac concept, so please excuse my ignorance)

How would I use this framework to check for the owner of an object? Is there a method to set roles based on rules?

Essentially my question is the same as is being answered in the second part of this post on SO: http://stackoverflow.com/a/9685039

**Comment by abiusx** [comment]
Great question, we should add some description to phprbac.net, as well as demo in phprbac.net/demo
this RBAC library is for function-level access control, it is optimized for lots of reads and minimal changes to its structure.
You can use it to add a permission for every record of data and bind it to its corresponding role (and user), and remove it once that record is used, but this use-case will it perform poorly. Every update to the role or permissions table requires a full-table-update, which might take up to a second on slow systems with large data-sets, but is perfectly fine as an administrative point of view (i.e when you're defining roles in your system).

This is initially intended for access to pages, functionality, applications segments and etc.

What do yo mean by rules BTW?

To use this with objects (objects usually have more than one functionality, and thus require more than one rbac check, but assuming its a single check), you can easily put $RBAC->Enforce("permission_here"); in your object's constructor. This will enforce the current user to have access to that object, or throw a forbidden http error.

**Comment by bblue** [comment]
I'll try to explain a bit more in-depth, and maybe the enforce method is what I need.

Consider an installation with the following hierarchy of roles: EDITOR, CONTRIBUTOR and GUEST

GUEST can access ARTICLE/VIEW, but only if the article object is published.
CONTRIBUTOR can access ARTICLE/EDIT, but only for his own articles.
EDITOR can access ARTICLE/EDIT of any article, as long as it is published

By rules I mean anything after the comma in the above sentences. i.e. some if/else statement that assigns/removes roles at runtime.

**Comment by abiusx** [comment]
You can do all of that, except one part, with an easy if statement in the following form:
if ($RBAC->Check("Your Desired Permission")) do_foo(); 

You can not easily handle "his own articles" because thats not functional access control, unless you add a permission for each article and assign it to each user, but you can check if an article is someone's or not, outside PHPRBAC's logic using your own app logic.

**Comment by bblue** [comment]
I suppose I was looking for a magic piece of code to assign roles before even accessing the object properties... 

I have been tripping over how to correctly implement a good access control architecture to my app for a while now, and I suppose I have been a bit blind, making it too complex in my mind.

Now reading my own post again, with you pointing out the obvious I think I got it:) Thanks for taking the time to reply :)

(As for rules, I see that Yii has some sort of bizrules in their rbac lib. I have not looked at it though, so I am not sure exactly what they use it for)

**Comment by abiusx** [comment]
Yii has an ACL, and just names is RBAC. It is very limited and small-scale. This lib supporst hierarchical roles and permissions, try the demo at phprbac.net/demo

**Comment by bblue** [comment]
I liked that demo, could not find a link to it before. You might want to make it even more obvious on your website how to access it.

Regarding my initial feature request, or whatever you would like to call it, I have been crunching over exactly what it was, and how to solve it for the past 24 hours. Your approach above would be feasible, but it would not be very flexible. I would like the possibility of ticking/unticking a box that gave a user permission to edit/delete his own post, and I would like to have that included in the existing RBAC lib.

Essentially what is needed is a 'permission group' that is outside the hierarchy of permissions. Before accessing $controller->edit() I would check if $user had any permission that made him part of the EDIT group. The rbac lib would then run through the permissions within the EDIT group, and check if user had any of those.

Given that the user indeed had one of those permissions I would enter the $controller->edit() method.

Within my $controller->edit() I would then check if the user had the permission of EDIT_ALL or EDIT_OWN based on what he was actually attempting to edit. This would be similar to your suggestion, but I would have the power control permissions on a much finer grade in my application.

Is my suggestion understandable? Is it feasible?

**Comment by jburns131** [comment]
Hello bblue and abuisx :-)

I've been a bit absent lately, but I'd like to throw in my two cents and see if I might be able to help here.

bblue, if I understand you correctly you might want to try this and see if it fits your needs:
- You can add the three permissions: 'view_article', 'edit_own_article' and 'edit_other_article'
- You can then add three roles, in a hierarchy: 'editor', which is the parent of 'contributor', which is the parent of 'guest'
- You can then assign permissions like this
  - guest -> view_articles
  - contributor -> edit_own_articles
  - editor -> edit_others_articles
- You will then have a role/permission hierarchy similar to this:
  - 'editor' HAS 'view_articles' AND 'edit_own_articles' AND 'edit_others_articles' permissions
  - 'contributor' HAS 'view_articles' AND 'edit_own_articles' permissions
  - 'guest' HAS 'view_articles' permission

Code Example:

``` php
$perm_id_1 = $rbac->Permissions->Add('edit_others_article');
$perm_id_2 = $rbac->Permissions->Add('edit_own_article');
$perm_id_3 = $rbac->Permissions->Add('view_article');

// Note that the returned role id is used as the third argument of the 'Add' method to form the proper hierarchy
$role_id_1 = $rbac->Role->Add('editor', 'The role for Editors');
$role_id_2 = $rbac->Role->Add('contributor', 'The role for Contributors', $role_id_1);
$role_id_3 = $rbac->Role->Add('guest', 'The role for Guests', $role_id_2);

$rbac->Roles->Assign($role_id_1, $perm_id_1);
$rbac->Roles->Assign($role_id_2, $perm_id_2);
$rbac->Roles->Assign($role_id_3, $perm_id_3);
```
- Now to assign a role to a user:

``` php
$rbac->Users->Assign($role_id_2, 5); // Second argument is dependent on you're own user id system
```
- Now add the proper check and balances. If the user is viewing an article that is not his own then check if they have the 'editor' role:

``` php
if ($rbac->Users->HasRole('editor', 5)) {
    // Allow the user to edit the article
} else {
    // Don't let them edit the article
}
```

You can also change this up and use 'Check' or 'Enforce' also, but I would probably use 'HasRole' in this situation. Or maybe even a combination of them depending on the granularity of the functionality in your system and permission/role scheme you come up with.

If I'm way off here please let me know and I'll play around some more to see if I might be able to suggest a better method.

**Comment by abiusx** [comment]
I was going to suggest something like that. You don’t need to escape hierarchy, you can always treat it as a flat model (just one depth of everything).

BTW I personally like to use PATHs, so the code Jesse gave you would be:
$role_id_1 = $rbac->Role->Add(‘/editor/contributor/guest’);

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by jburns131** [comment]
Thank you Abbas,

I actually had a question about the paths and assignments.

I was going to use a path for the roles in my example above, but when assigning permissions to roles using '$rbac->Roles->Assign()' we need to use the role id, i.e. an integer. I thought the above would be a little simpler since it's all happening in one script.

If I'm correct, the alternative to my method above would be to add roles using the 'AddPath' method, but then we'd need to get the role_id using the 'PathId' method in order to use the 'Roles->Assign' method. Is this correct?

The Roles/Permissions 'Assign' method is different than the Users 'Assign' method:
- Roles->Assign() and Permissions->Assign() only take integers as their arguments
- The Users->Assign method will take an id, path or title as it's first argument

**Comment by abiusx** [comment]
Lets add a wrapper that accepts paths then!

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by jburns131** [comment]
That sounds good. I'll open a new Issue for that.

P.S. I think you might want to change your example in the last comment Abbas, as I believe the 'Add' method only accepts a title, not paths. Please correct me if I am mistaken. Thanks!

**Comment by abiusx** [comment]
You’re right :d Lets have people read this instead of copy paste.
-A

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by bblue** [comment]
@jburns131 That will force me to allow all users to access the given controller and method, but come to think of it that is probably just as well as it will complete my authorization in a single step, not two as with my own suggested approach. I will be testing over the weekend, but think I got it now. Thanks to both of you.

That being said, I still see some value in the possibility of assigning temporary roles or permissions at runtime, as the title of this thread suggests.

**Comment by abiusx** [comment]
Well thats not a good idea, data-level access control should be part of the application logic, i.e you should have a permission or role “pinned” to every record of  data inside your database, and never forget to check for them. there are models and theories for that, but I haven’t worked on those yet.
-A

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by jburns131** [comment]
Hi again @bblue ,

I think there might be some confusion due to you being new to Rbac systems, or just new to PhpRbac, but I may be wrong.

I'll try to clarify some things and help you understand:
- Why we are making the suggestions we are making
- A few details regarding how the system works
- The paradigm shift you might need to make when thinking about your own permission system and it's design

I'm not quite as knowledgeable as @abiusx is, but I have learned a few things while helping with the project and using PhpRbac in my project.

@abiusx, if I am incorrect about any information I share here please correct me.

**My Understanding Of What An Rbac System Is**

First of all, my understanding of what an Rbac system is:
- To define labels for roles and permissions
- To manipulate role-to-permission associations
- To assign roles to users
- Offer methods that enable you to query those associations, i.e.
  - To find out if a user has a role/permission
  - To find out if a role has a specific permission
  - To find out if a role or permission has a child or parent
  - etc...

But all the system does is maintain those labels and relations in an efficient manner, and perform highly efficient queries regarding the complex hierarchy of roles and permission.

It is up to your application logic to define what your software does when a user has a specific role or permission.

An Rbac system does not define application logic rules that are designed to respond to a users role/permission association. All it does is maintain the creation, reading, updating and deleting of those associations.

**Why You Don't Want Application Logic To Manipulate Roles/Permissions Often**

The internal database structure consists of a hierarchy of roles and a hierarchy of permissions. This data is stored as Nested Lists.

You might want to take a look at this article before continuing:

[Nested set model](http://en.wikipedia.org/wiki/Nested_set_model) 

One of the most innovative and beautiful aspects of PhpRbac is that it offers an efficient and simple interface to very complex operations and data manipulation.

But because of the nature of Nested Lists, all hierarchy changes trickle down from the parent to the child. This means that even if you think you are just adding a child, or even a sibling role or permission, the system needs to alter the internal data structure for (almost) every role or permission entry in the database. For almost any mid-to-large role/permission structure/system this is a large and time consuming task.

If you have an admin section in your application that allows you to create, alter and remove roles, permissions and associations, then it isn't all that taxing because you are only changing the data structure periodically. But if almost every page load needs to do the same thing then there is a lot of data manipulation going on all the time.

This is why @abiusx mentioned:

> [PhpRbac] is optimized for lots of reads and minimal changes to its structure.
> 
> You can use it to add a permission for every record of data and bind it to its corresponding role (and user), and remove it once that record is used, but this use-case will it perform poorly. Every update to the role or permissions table requires a full-table-update, which might take up to a second on slow systems with large data-sets, but is perfectly fine as an administrative point of view (i.e when you're defining roles in your system).

**My Suggestion**

I would think of your permission system as having at least two parts:
1. One part is using an Rbac system to define and manipulate role/permission/user hierarchies and associations. 
2. The other part is your application logic which defines how the system behaves based upon a user's/object's defined roles and permissions.

Because of PhpRbac's flexibility and ease of use regarding how you design your role/permission hierarchies and associations, you have virtually no limitations as to how you decide to build your role/permission associations and the application logic rules that are used to enforce them.

I hope this helped, and I hope I have not been misleading or misinformed.

@bblue: If you would like chat then feel free to hit me up on skype, my username is: jburns131

**Comment by bblue** [comment]
Hello @jburns131. Thank you very much for such a detailed explanation. My apologies for not replying earlier, but I have been a away for some days. I will sit down and have a proper read through your post at first opportunity. I am likely to have some questions, so I might also take you on the Skype invitation.

**Comment by jburns131** [comment]
Absolutely, I am here if needed :-)

**Comment by jburns131** [comment]
I have compiled a list of links that discuss advanced topics regarding RBAC.

These articles will give you a better understanding of what RBAC is, what it's strengths are, and the proper construction and use of RBAC policies, just to name a few things.

Knowledge of these advanced topics and resources will better help developers design a secure and flexible access control system using PHP-RBAC as it's backbone.

First of all, the NIST RBAC Group web page is a plethora of excellent information regarding RBAC:

[NIST RBAC Group](http://csrc.nist.gov/groups/SNS/rbac/index.html)
[Official RBAC Standard](http://csrc.nist.gov/rbac/sandhu-ferraiolo-kuhn-00.pdf)
[Case Study, SANS Institute - RBAC In The Real World](https://www.sans.org/reading-room/whitepapers/casestudies/rbac-real-world-772?show=rbac-real-world-772&cat=casestudies)
[Case Study, SP&E - Development of a RBAC Policy-Writing Tool](http://www.cs.kent.ac.uk/pubs/2005/2275/content.pdf)
[RBAC Standard Rationale](http://csrc.nist.gov/groups/SNS/rbac/documents/ferraiolo-kuhn-sandhu-07.pdf)

That should get you on the right track.

**Comment by jburns131** [comment]
I will be closing this issue in the next few days if this issue remains inactive.

**Comment by jburns131** [comment]
This Issue does not address problem with PHP-RBAC.

This Issue addresses a question regarding implementation.

Closing Issue.
