### ISSUE TITLE
why are you not passing config parameters as a POST ?

### ISSUE THREAD

**Issue by udf2457** [OWASP/rbac#33]
Why are you exposing all the config parameters passed  to install.php in the URL as a GET ?

POST seems like a more sensible option ?

**Comment by abiusx** [comment]
Its not very different, the installer script is just a way of showing how you can use the library. as mentioned before, a library does not need installation and error reporting. its only there because installation seemed a little hard to do manually.
Did you follow the docs on the website? was there something flawed?
Thanks

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by udf2457** [comment]
Well, I went to install.php as directed, filled in the form... clicked POST and then got a whole bunch of errors as described in the other ticket.

**Comment by abiusx** [comment]
please update the other ticket with you platform, so that we can reproduce

---

Notice: This message is digitally signed, its source and integrity are verifiable.
If you mail client does not support S/MIME verification, it will display a file (smime.p7s), which includes the X.509 certificate and the signature body.  Read more at Certified E-Mail with Comodo and Thunderbird in AbiusX.com

**Comment by jburns131** [comment]
Another reason we are using GET is because install.php should only be used once and then removed. It should not be used by general users, hence there isn't a need for great security.

I will be sure to add 'delete install.php' to the installation instructions.

**Comment by Kern046** [comment]
Hello there,

Don't you think that a CLI script would be better ?

I believe that the install script musn't be removed when the database is created. In long-term projects, databases credentials can change, and being able to update it with command line would be useful.

Security will also be better, because that script will be executed only by users with direct access on the server, which is more relievable than supposing the RBAC users will delete the install.php file.

(PS: Sorry for my poor english, I still have a lot of work to do to improve it :p)

**Comment by jburns131** [comment]
We have decided that any supporting tools/functionality for PHP-RBAC will be hosted under the "FriendsOf-PhpRbac" Github Organization (https://github.com/FriendsOf-PhpRbac).

As an installation script is not part of the core library I have removed the installation script and will decide which proposed installation tool to host on "FriendsOf-PhpRbac" at a later date.
