### ISSUE TITLE
Duplicated "Titles" are allowed?

### ISSUE THREAD

**Issue by leo-combes** [OWASP/rbac#61]
Apparently it is possible to add more of a permission or role with the same name. I guess this can be a problem if later they be referred to it by index or by name.
For example, in practice you can do this:

$rbac->Roles->add("forum_admin", "test");
...role created whit ID #2

$rbac->Roles->add("forum_admin", "test2");
...role created whit ID #3

Now, we have two different roles with the same name.

When I need to get role ID, I can do this:

$rbac->Roles->returnId("forum_admin");
... return #2

However, the databases contains the two roles named "forum_admin":

mysql> select \* from phprbac_roles;
+----+-----+------+-------------+-------------+
| ID | Lft | Rght | Title       | Description |
+----+-----+------+-------------+-------------+
|  1 |   0 |   23 | root        | root        |
|  2 |  19 |   20 | forum_admin | test        |
|  3 |  21 |   22 | forum_admin | test2       |
+----+-----+------+-------------+-------------+
3 rows in set (0.01 sec)

The problem is in cases where functions accepts differents ways to identify a entity, for example:

Rbac -> {Entidad} -> assign()

Accepts one of the following:

```
int ID
string Title
string Path
```

I can use ID=3 or Title="forum_admin"... but if I use Roles->returnId("forum_admin") the function tells me that ID is #2.

I think allow duplicate names can trigger unwanted situations
It would be good apply the attribute "UNIQUE" in "Title" columns and that duplicate names are not allowed?

**Comment by abiusx** [comment]
I believe this has been discussed before.
This is intentional. Though you are able to create two same titles under the same node, you will not likely do that, and would place them under different parents.
e.g

/management/door
/vault/door

Both of which have a node titled “door”. If you have such a system, you can point to different nodes using “paths”. Otherwise you can use titles. Uniqueness constraint should not be forced otherwise many valid usages will be denied. Check under each parent is not wise as it will significantly slow the library.
-A

**Comment by leo-combes** [comment]
Now I see why this could be useful.
Thanks for your explanation!
