### ISSUE TITLE
Roles/Permission Inheritance 

### ISSUE THREAD

**Issue by KnightYoshi** [OWASP/rbac#93]
So the example uses `$myPath = '/blog_admin/blog_editor/blog_writer/blog_member';` Does blog_admin inherit the permissions from each role below it? Also how does inheritance work with permissions, is it recommended to use inheritance for permissions?

I was thinking of having permissions based on the URL path, so something like ` 'news/view'`, `'news/create'`, `'news/edit'`, `'news/delete'`, `'news/publish'`, `'news/delete'`

- member would only have permission to view 
- writer could view, create, and edit (obviously only theirs, but that's separate), 
- editor could view, create, edit, publish and delete
- admin would have all that and more

I'm relatively new to using RBAC so please bear with me. :)

**Comment by abiusx** [comment]
Think of it as a hierarchy of permissions rather than inheritance.
For example "/door/vault_door" and "/door/office_door". door is the parent permission, and if someone has it, s/he has all the child permissions as well. That is less confusing.
Yes, the major purpose of this library is to use permission hierarchy. Role hierarhcy has meaning, but permission hierarchy has even more meaning!

In your example, you have to establish the relationship between those permissions yourself rather than in the hiararchy. Write can not necessarily view, but in your system can. So you can force "view or write" on view. Admin will just have the root permission.
Or you can give write the whole "news" permission, that would be more structured.
